/**
 * Recipes that exist in Create but were missing from the Create Bedrock addon.
 *
 * Generated by tools/gen_recipes.py - do not edit by hand.
 *
 * The list was produced by diffing Create 1.21.1's recipe data against the
 * tables built into the Bedrock addon, then dropping anything whose items do
 * not exist on Bedrock. Every id below is one the Bedrock addon defines.
 */

/**
 * Crushing Wheel recipes Create has but Bedrock was missing -
 * mostly the decorative stone family, which the addon ships as blocks
 * but could not crush, plus zinc ore and a few vanilla oddities.
 */
export const CRUSHING = [
    {
        input: "create:asurine",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:cut_asurine",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:cut_asurine_bricks",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:cut_asurine_stairs",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:polished_cut_asurine",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:polished_cut_asurine_stairs",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:small_asurine_bricks",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.3
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.3
            }
        ]
    },
    {
        input: "create:crimsite",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:cut_crimsite",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:cut_crimsite_bricks",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:cut_crimsite_stairs",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:polished_cut_crimsite",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:polished_cut_crimsite_stairs",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:small_crimsite_bricks",
        duration: 250,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_iron",
                count: 1,
                chance: 0.4
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.4
            }
        ]
    },
    {
        input: "create:deepslate_zinc_ore",
        duration: 350,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 2
            },
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.25
            },
            {
                item: "create:experience_nugget",
                count: 1,
                chance: 0.75
            },
            {
                item: "minecraft:cobbled_deepslate",
                count: 1,
                chance: 0.125
            }
        ]
    },
    {
        input: "create:cut_diorite",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:cut_diorite_bricks",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:cut_diorite_stairs",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:polished_cut_diorite",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:polished_cut_diorite_stairs",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:small_diorite_bricks",
        duration: 350,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:gilded_blackstone",
        duration: 400,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:gold_nugget",
                count: 18
            },
            {
                item: "create:experience_nugget",
                count: 1,
                chance: 0.75
            },
            {
                item: "minecraft:blackstone",
                count: 1,
                chance: 0.125
            }
        ]
    },
    {
        input: "minecraft:nether_wart_block",
        duration: 150,
        particleRGB: {
            red: 0.45,
            green: 0.1,
            blue: 0.12,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:nether_wart",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "create:ochrum",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:cut_ochrum",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:cut_ochrum_bricks",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:cut_ochrum_stairs",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:polished_cut_ochrum",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:polished_cut_ochrum_stairs",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "create:small_ochrum_bricks",
        duration: 250,
        particleRGB: {
            red: 0.95,
            green: 0.8,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_gold",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.2
            }
        ]
    },
    {
        input: "minecraft:prismarine_crystals",
        duration: 150,
        particleRGB: {
            red: 0.93,
            green: 0.9,
            blue: 0.86,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:quartz",
                count: 1
            },
            {
                item: "minecraft:quartz",
                count: 2,
                chance: 0.5
            },
            {
                item: "minecraft:glowstone_dust",
                count: 2,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:tuff",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:cut_tuff",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:cut_tuff_bricks",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:cut_tuff_stairs",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:polished_cut_tuff",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:polished_cut_tuff_stairs",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:small_tuff_bricks",
        duration: 350,
        particleRGB: {
            red: 0.35,
            green: 0.33,
            blue: 0.32,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:flint",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:gold_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "create:zinc_nugget",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:iron_nugget",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "create:veridium",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:cut_veridium",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:cut_veridium_bricks",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:cut_veridium_stairs",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:polished_cut_veridium",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:polished_cut_veridium_stairs",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:small_veridium_bricks",
        duration: 250,
        particleRGB: {
            red: 0.85,
            green: 0.5,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_copper",
                count: 1,
                chance: 0.8
            },
            {
                item: "create:copper_nugget",
                count: 1,
                chance: 0.8
            }
        ]
    },
    {
        input: "create:zinc_ore",
        duration: 250,
        particleRGB: {
            red: 0.78,
            green: 0.8,
            blue: 0.83,
            alpha: 1
        },
        outputs: [
            {
                item: "create:crushed_raw_zinc",
                count: 1
            },
            {
                item: "create:crushed_raw_zinc",
                count: 1,
                chance: 0.75
            },
            {
                item: "create:experience_nugget",
                count: 1,
                chance: 0.75
            },
            {
                item: "minecraft:cobblestone",
                count: 1,
                chance: 0.125
            }
        ]
    }
];

/**
 * Millstone recipes missing from the Bedrock tables.
 */
export const MILLSTONE = [
    {
        input: "minecraft:pink_petals",
        duration: 50,
        particleRGB: {
            red: 0.95,
            green: 0.55,
            blue: 0.74,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:pink_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:pitcher_plant",
        duration: 50,
        particleRGB: {
            red: 0.09,
            green: 0.61,
            blue: 0.61,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:cyan_dye",
                count: 4
            },
            {
                item: "minecraft:purple_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:hardened_clay",
        duration: 200,
        particleRGB: {
            red: 0.76,
            green: 0.4,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_sand",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:torchflower",
        duration: 50,
        particleRGB: {
            red: 0.98,
            green: 0.5,
            blue: 0.11,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:orange_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.1
            }
        ]
    }
];

/**
 * Create lets a Crushing Wheel run a milling recipe when the item has
 * no dedicated crushing recipe. Bedrock's wheel never did, so these
 * mirror the Millstone table into the wheel.
 */
export const CRUSHING_FROM_MILLING = [
    {
        input: "minecraft:allium",
        duration: 50,
        particleRGB: {
            red: 0.75,
            green: 0.3,
            blue: 0.75,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:magenta_dye",
                count: 2
            },
            {
                item: "minecraft:purple_dye",
                count: 2,
                chance: 0.1
            },
            {
                item: "minecraft:pink_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:azure_bluet",
        duration: 50,
        particleRGB: {
            red: 0.9,
            green: 0.9,
            blue: 0.95,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:light_gray_dye",
                count: 2
            },
            {
                item: "minecraft:white_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:beetroot",
        duration: 70,
        particleRGB: {
            red: 0.7,
            green: 0.15,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_dye",
                count: 2
            },
            {
                item: "minecraft:beetroot_seeds",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:black_wool",
        duration: 100,
        particleRGB: {
            red: 0.1,
            green: 0.1,
            blue: 0.1,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:blue_orchid",
        duration: 50,
        particleRGB: {
            red: 0.3,
            green: 0.6,
            blue: 0.9,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:light_blue_dye",
                count: 2
            },
            {
                item: "minecraft:light_gray_dye",
                count: 1,
                chance: 0.05
            }
        ]
    },
    {
        input: "minecraft:blue_wool",
        duration: 100,
        particleRGB: {
            red: 0.2,
            green: 0.25,
            blue: 0.7,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:bone_meal",
        duration: 70,
        particleRGB: {
            red: 0.9,
            green: 0.9,
            blue: 0.85,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:white_dye",
                count: 2
            },
            {
                item: "minecraft:light_gray_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:brown_wool",
        duration: 100,
        particleRGB: {
            red: 0.45,
            green: 0.3,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:cactus",
        duration: 50,
        particleRGB: {
            red: 0.2,
            green: 0.55,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:green_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:calcite",
        duration: 250,
        particleRGB: {
            red: 0.9,
            green: 0.88,
            blue: 0.85,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:bone_meal",
                count: 1,
                chance: 0.12
            }
        ]
    },
    {
        input: "minecraft:clay",
        duration: 50,
        particleRGB: {
            red: 0.65,
            green: 0.62,
            blue: 0.58,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:clay_ball",
                count: 3
            },
            {
                item: "minecraft:clay_ball",
                count: 1,
                chance: 0.5
            }
        ]
    },
    {
        input: "minecraft:cocoa_beans",
        duration: 70,
        particleRGB: {
            red: 0.45,
            green: 0.25,
            blue: 0.1,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:brown_dye",
                count: 2
            },
            {
                item: "minecraft:brown_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:cornflower",
        duration: 50,
        particleRGB: {
            red: 0.25,
            green: 0.35,
            blue: 0.8,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:blue_dye",
                count: 2
            }
        ]
    },
    {
        input: "minecraft:cyan_wool",
        duration: 100,
        particleRGB: {
            red: 0.1,
            green: 0.5,
            blue: 0.55,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:dandelion",
        duration: 50,
        particleRGB: {
            red: 0.95,
            green: 0.9,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:yellow_dye",
                count: 2
            },
            {
                item: "minecraft:yellow_dye",
                count: 1,
                chance: 0.05
            }
        ]
    },
    {
        input: "minecraft:dripstone_block",
        duration: 250,
        particleRGB: {
            red: 0.55,
            green: 0.45,
            blue: 0.38,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:clay_ball",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:fern",
        duration: 50,
        particleRGB: {
            red: 0.3,
            green: 0.55,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:green_dye",
                count: 1
            },
            {
                item: "minecraft:wheat_seeds",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:gray_wool",
        duration: 100,
        particleRGB: {
            red: 0.4,
            green: 0.4,
            blue: 0.4,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:green_wool",
        duration: 100,
        particleRGB: {
            red: 0.3,
            green: 0.4,
            blue: 0.1,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:hardened_clay",
        duration: 200,
        particleRGB: {
            red: 0.76,
            green: 0.4,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_sand",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:ink_sac",
        duration: 70,
        particleRGB: {
            red: 0.1,
            green: 0.1,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:black_dye",
                count: 2
            },
            {
                item: "minecraft:gray_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:lapis_lazuli",
        duration: 100,
        particleRGB: {
            red: 0.15,
            green: 0.2,
            blue: 0.7,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:blue_dye",
                count: 2
            },
            {
                item: "minecraft:blue_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:large_fern",
        duration: 50,
        particleRGB: {
            red: 0.3,
            green: 0.55,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:green_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.5
            },
            {
                item: "minecraft:wheat_seeds",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:light_blue_wool",
        duration: 100,
        particleRGB: {
            red: 0.5,
            green: 0.7,
            blue: 0.9,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:light_gray_wool",
        duration: 100,
        particleRGB: {
            red: 0.65,
            green: 0.65,
            blue: 0.65,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:lilac",
        duration: 50,
        particleRGB: {
            red: 0.7,
            green: 0.4,
            blue: 0.7,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:magenta_dye",
                count: 3
            },
            {
                item: "minecraft:magenta_dye",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:purple_dye",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:lily_of_the_valley",
        duration: 50,
        particleRGB: {
            red: 0.95,
            green: 0.95,
            blue: 0.95,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:white_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            },
            {
                item: "minecraft:white_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:lime_wool",
        duration: 100,
        particleRGB: {
            red: 0.5,
            green: 0.75,
            blue: 0.1,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:magenta_wool",
        duration: 100,
        particleRGB: {
            red: 0.75,
            green: 0.3,
            blue: 0.75,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:orange_tulip",
        duration: 50,
        particleRGB: {
            red: 0.9,
            green: 0.55,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:orange_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:orange_wool",
        duration: 100,
        particleRGB: {
            red: 0.9,
            green: 0.55,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:oxeye_daisy",
        duration: 50,
        particleRGB: {
            red: 0.9,
            green: 0.9,
            blue: 0.85,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:light_gray_dye",
                count: 2
            },
            {
                item: "minecraft:white_dye",
                count: 1,
                chance: 0.2
            },
            {
                item: "minecraft:yellow_dye",
                count: 1,
                chance: 0.05
            }
        ]
    },
    {
        input: "minecraft:peony",
        duration: 50,
        particleRGB: {
            red: 0.9,
            green: 0.6,
            blue: 0.7,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:pink_dye",
                count: 3
            },
            {
                item: "minecraft:magenta_dye",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:pink_dye",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:pink_petals",
        duration: 50,
        particleRGB: {
            red: 0.95,
            green: 0.55,
            blue: 0.74,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:pink_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:pink_tulip",
        duration: 50,
        particleRGB: {
            red: 0.9,
            green: 0.55,
            blue: 0.65,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:pink_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:pink_wool",
        duration: 100,
        particleRGB: {
            red: 0.9,
            green: 0.55,
            blue: 0.65,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:pitcher_plant",
        duration: 50,
        particleRGB: {
            red: 0.09,
            green: 0.61,
            blue: 0.61,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:cyan_dye",
                count: 4
            },
            {
                item: "minecraft:purple_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:poppy",
        duration: 50,
        particleRGB: {
            red: 0.85,
            green: 0.15,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.05
            }
        ]
    },
    {
        input: "minecraft:purple_wool",
        duration: 100,
        particleRGB: {
            red: 0.5,
            green: 0.15,
            blue: 0.75,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:red_tulip",
        duration: 50,
        particleRGB: {
            red: 0.85,
            green: 0.2,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:red_wool",
        duration: 100,
        particleRGB: {
            red: 0.8,
            green: 0.15,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:rose_bush",
        duration: 50,
        particleRGB: {
            red: 0.8,
            green: 0.15,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_dye",
                count: 3
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.05
            },
            {
                item: "minecraft:red_dye",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:saddle",
        duration: 150,
        particleRGB: {
            red: 0.55,
            green: 0.3,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:leather",
                count: 2
            },
            {
                item: "minecraft:leather",
                count: 2,
                chance: 0.5
            }
        ]
    },
    {
        input: "minecraft:sandstone",
        duration: 150,
        particleRGB: {
            red: 0.85,
            green: 0.8,
            blue: 0.55,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:sand",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:sea_pickle",
        duration: 50,
        particleRGB: {
            red: 0.45,
            green: 0.6,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:lime_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:short_grass",
        duration: 50,
        particleRGB: {
            red: 0.4,
            green: 0.6,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:wheat_seeds",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:sugar_cane",
        duration: 50,
        particleRGB: {
            red: 0.5,
            green: 0.75,
            blue: 0.3,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:sugar",
                count: 2
            },
            {
                item: "minecraft:sugar",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:sunflower",
        duration: 50,
        particleRGB: {
            red: 0.95,
            green: 0.85,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:yellow_dye",
                count: 3
            },
            {
                item: "minecraft:orange_dye",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:yellow_dye",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:tall_grass",
        duration: 50,
        particleRGB: {
            red: 0.4,
            green: 0.6,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:wheat_seeds",
                count: 1,
                chance: 0.5
            }
        ]
    },
    {
        input: "minecraft:terracotta",
        duration: 150,
        particleRGB: {
            red: 0.6,
            green: 0.38,
            blue: 0.25,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:red_sand",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:torchflower",
        duration: 50,
        particleRGB: {
            red: 0.98,
            green: 0.5,
            blue: 0.11,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:orange_dye",
                count: 2
            },
            {
                item: "minecraft:green_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:wheat",
        duration: 100,
        particleRGB: {
            red: 0.85,
            green: 0.75,
            blue: 0.45,
            alpha: 1
        },
        outputs: [
            {
                item: "create:wheat_flour",
                count: 1
            },
            {
                item: "create:wheat_flour",
                count: 1,
                chance: 0.25
            },
            {
                item: "minecraft:wheat_seeds",
                count: 1,
                chance: 0.25
            }
        ]
    },
    {
        input: "minecraft:white_tulip",
        duration: 50,
        particleRGB: {
            red: 0.92,
            green: 0.92,
            blue: 0.92,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:white_dye",
                count: 2
            },
            {
                item: "minecraft:lime_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:white_wool",
        duration: 100,
        particleRGB: {
            red: 0.95,
            green: 0.95,
            blue: 0.95,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    },
    {
        input: "minecraft:wither_rose",
        duration: 50,
        particleRGB: {
            red: 0.15,
            green: 0.15,
            blue: 0.15,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:black_dye",
                count: 2
            },
            {
                item: "minecraft:black_dye",
                count: 1,
                chance: 0.1
            }
        ]
    },
    {
        input: "minecraft:yellow_wool",
        duration: 100,
        particleRGB: {
            red: 0.95,
            green: 0.9,
            blue: 0.2,
            alpha: 1
        },
        outputs: [
            {
                item: "minecraft:string",
                count: 1
            }
        ]
    }
];

/**
 * Bulk Washing (fan + water).
 */
export const SPLASHING = [
    {
        input: "create:industrial_iron_block",
        outputs: [
            {
                item: "create:weathered_iron_block",
                count: 1
            }
        ]
    },
    {
        input: "create:industrial_iron_window",
        outputs: [
            {
                item: "create:weathered_iron_window",
                count: 1
            }
        ]
    }
];

/**
 * Bulk Haunting (fan + soul fire).
 */
export const HAUNTING = [];

/**
 * Bulk Smelting / melting (fan + lava or fire).
 */
export const BLASTING = [];

/**
 * Bulk Smoking (fan + campfire).
 */
export const SMOKING = [];

/**
 * Mechanical Press recipes missing on Bedrock.
 */
export const PRESSING = [
    {
        input: "minecraft:dirt",
        output: "minecraft:dirt_path"
    },
    {
        input: "minecraft:coarse_dirt",
        output: "minecraft:dirt_path"
    },
    {
        input: "minecraft:rooted_dirt",
        output: "minecraft:dirt_path"
    },
    {
        input: "minecraft:mycelium",
        output: "minecraft:dirt_path"
    },
    {
        input: "minecraft:podzol",
        output: "minecraft:dirt_path"
    },
    {
        input: "minecraft:grass_block",
        output: "minecraft:dirt_path"
    }
];

/**
 * Mechanical Mixer recipes missing on Bedrock.
 */
export const MIXING = [];

/**
 * Corrections to existing Bedrock recipes that referenced items which
 * do not exist. Compatibility recipes are matched before the built-in
 * tables, so registering these replaces the broken ones.
 */
export const SPLASHING_FIXES = [
    {
        input: "create:crushed_raw_copper",
        outputs: [
            {
                item: "minecraft:copper_ingot",
                count: 1
            },
            {
                item: "minecraft:clay_ball",
                count: 1,
                chance: 0.5
            }
        ]
    }
];

/**
 * Mechanical Crafter recipes. The Crushing Wheel is the important one:
 * the Bedrock addon's crafter already knows how to match a 5x5 pattern
 * (its own code comments mention the wheel) but the recipe was never
 * registered, leaving Crushing Wheels uncraftable.
 */
export const MECHANICAL_CRAFTING = [
    {
        pattern: [
            " AAA ",
            "AAPAA",
            "APSPA",
            "AAPAA",
            " AAA "
        ],
        key: {
            A: {
                item: "create:andesite_alloy"
            },
            P: {
                tag: "minecraft:planks"
            },
            S: {
                item: "minecraft:stone"
            }
        },
        result: {
            id: "create:crushing_wheel",
            amount: 2
        }
    }
];

/**
 * Spout filling recipes missing on Bedrock.
 */
export const SPOUTING = [];

/**
 * Sequenced assembly recipes missing on Bedrock.
 */
export const SEQUENCED = [];

/** Total recipes added by More Create. */
export const TOTAL = 116;
