#!/usr/bin/env python3
"""Split CHANGELOG.md into one release-note file per version, and write the
script that publishes them to GitHub's Releases tab.

The session that develops this repository cannot create releases directly -
pushing a tag comes back 403, `api.github.com/repos/*` is blocked at its proxy,
and its GitHub tooling only reads releases. So the script runs in GitHub Actions
instead (`.github/workflows/publish-releases.yml`), where the repository's own
token has `contents: write`. It is an ordinary shell script, so it also works
from any machine with the GitHub CLI authenticated.

The notes are split rather than written twice, so the Releases tab and the
changelog can never drift apart.

Usage: gen_release_notes.py
"""

import os
import re
import stat
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHANGELOG = os.path.join(ROOT, "CHANGELOG.md")
NOTES_DIR = os.path.join(ROOT, "dist/release-notes")
SCRIPT_OUT = os.path.join(ROOT, "tools/publish_releases.sh")

REPO = "lhetvillanueva2000-maker/More-Create"
# Releases are cut from the branch the work lives on.
TARGET = "claude/more-create-bedrock-mod-ccmzb3"


def build_commit(asset):
    """The commit that added a build, so its tag points at the real thing.

    Falls back to the branch when the file is not committed yet, which is what
    happens the first time a new version is generated before it is committed.
    """
    try:
        sha = subprocess.run(
            ["git", "log", "--diff-filter=A", "--format=%H", "-1", "--", asset],
            cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return TARGET
    return sha or TARGET


def sections():
    """Yield (version, heading, body) for each `## vX.Y — ...` block."""
    text = open(CHANGELOG, encoding="utf-8").read()
    pattern = re.compile(r"^## (v\d+\.\d+)\s*(?:[—-]\s*(.*))?$", re.M)
    marks = list(pattern.finditer(text))
    for index, match in enumerate(marks):
        end = marks[index + 1].start() if index + 1 < len(marks) else len(text)
        body = text[match.end():end]
        # Drop the horizontal rule that separates one version from the next.
        body = re.sub(r"\n---\s*$", "", body.strip()) .strip()
        yield match.group(1), (match.group(2) or "").strip(), body


def main():
    os.makedirs(NOTES_DIR, exist_ok=True)
    found = list(sections())
    if not found:
        raise SystemExit("no version sections found in CHANGELOG.md")

    lines = [
        "#!/usr/bin/env bash",
        "#",
        "# Publish every More Create build to the repository's Releases tab.",
        "#",
        "# Generated by tools/gen_release_notes.py - re-run that after editing",
        "# CHANGELOG.md so the notes here stay in step.",
        "#",
        "# Needs the GitHub CLI, authenticated as someone who can write to the",
        "# repository:",
        "#",
        "#     gh auth login",
        "#     bash tools/publish_releases.sh",
        "#",
        "# Safe to re-run: a version that already has a release is skipped.",
        "",
        "set -euo pipefail",
        "",
        'cd "$(dirname "$0")/.."',
        "",
        'REPO="%s"' % REPO,
        '# Each tag points at the commit that actually added that build.',
        "",
        "publish() {",
        '    local tag="$1" title="$2" notes="$3" asset="$4" target="$5" extra="${6:-}"',
        "",
        '    if [ ! -f "$asset" ]; then',
        '        echo "skip $tag: $asset is missing"',
        "        return",
        "    fi",
        '    if gh release view "$tag" --repo "$REPO" >/dev/null 2>&1; then',
        '        echo "skip $tag: release already exists"',
        "        return",
        "    fi",
        "",
        '    echo "publishing $tag ..."',
        '    # shellcheck disable=SC2086 # $extra is deliberately word-split',
        '    gh release create "$tag" "$asset" \\',
        '        --repo "$REPO" \\',
        '        --target "$target" \\',
        '        --title "$title" \\',
        '        --notes-file "$notes" $extra',
        "}",
        "",
    ]

    latest = found[-1][0]
    print("release notes ->", os.path.relpath(NOTES_DIR, ROOT))
    for version, heading, body in found:
        note_path = os.path.join(NOTES_DIR, version + ".md")
        asset = "dist/MoreCreate-%s.mcaddon" % version
        title = "More Create %s" % version + (" - %s" % heading if heading else "")

        with open(note_path, "w", encoding="utf-8") as handle:
            handle.write("# %s\n\n" % title)
            handle.write(body.rstrip() + "\n\n")
            handle.write("---\n\n")
            handle.write(
                "Requires Minecraft Bedrock **1.26.13** or newer, with "
                "Vatonage's **Create** behaviour and resource packs enabled on "
                "the world.\n\nDownload `MoreCreate-%s.mcaddon` below and open "
                "it to import both packs.\n" % version)

        exists = os.path.isfile(os.path.join(ROOT, asset))
        print("  %-6s %-28s %5d bytes of notes%s"
              % (version, os.path.basename(note_path), len(body),
                 "" if exists else "   WARNING: no .mcaddon built"))

        extra = '--latest' if version == latest else '--latest=false'
        lines.append('publish "%s" "%s" "%s" "%s" "%s" "%s"'
                     % (version, title,
                        "dist/release-notes/%s.md" % version, asset,
                        build_commit(asset), extra))

    lines += ["", 'echo "done - https://github.com/$REPO/releases"', ""]

    with open(SCRIPT_OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    os.chmod(SCRIPT_OUT, os.stat(SCRIPT_OUT).st_mode | stat.S_IEXEC)
    print("wrote %s (%d releases)"
          % (os.path.relpath(SCRIPT_OUT, ROOT), len(found)))


if __name__ == "__main__":
    main()
