#!/usr/bin/env bash
#
# Publish every More Create build to the repository's Releases tab.
#
# Generated by tools/gen_release_notes.py - re-run that after editing
# CHANGELOG.md so the notes here stay in step.
#
# Needs the GitHub CLI, authenticated as someone who can write to the
# repository:
#
#     gh auth login
#     bash tools/publish_releases.sh
#
# Safe to re-run: a version that already has a release is skipped.

set -euo pipefail

cd "$(dirname "$0")/.."

REPO="lhetvillanueva2000-maker/More-Create"
# Each tag points at the commit that actually added that build.

publish() {
    local tag="$1" title="$2" notes="$3" asset="$4" target="$5" extra="${6:-}"

    if [ ! -f "$asset" ]; then
        echo "skip $tag: $asset is missing"
        return
    fi
    if gh release view "$tag" --repo "$REPO" >/dev/null 2>&1; then
        echo "skip $tag: release already exists"
        return
    fi

    echo "publishing $tag ..."
    # shellcheck disable=SC2086 # $extra is deliberately word-split
    gh release create "$tag" "$asset" \
        --repo "$REPO" \
        --target "$target" \
        --title "$title" \
        --notes-file "$notes" $extra
}

publish "v1.0" "More Create v1.0 - what More Create is" "dist/release-notes/v1.0.md" "dist/MoreCreate-v1.0.mcaddon" "d350b27bca7d20a22c701c1499f3c2fe719a1181" "--latest=false"
publish "v1.1" "More Create v1.1 - everything new" "dist/release-notes/v1.1.md" "dist/MoreCreate-v1.1.mcaddon" "d350b27bca7d20a22c701c1499f3c2fe719a1181" "--latest=false"
publish "v1.2" "More Create v1.2 - more added" "dist/release-notes/v1.2.md" "dist/MoreCreate-v1.2.mcaddon" "d350b27bca7d20a22c701c1499f3c2fe719a1181" "--latest=false"
publish "v1.3" "More Create v1.3 - fixes and the Recipe Book" "dist/release-notes/v1.3.md" "dist/MoreCreate-v1.3.mcaddon" "d350b27bca7d20a22c701c1499f3c2fe719a1181" "--latest=false"
publish "v1.4" "More Create v1.4 - the Schematic Cannon screen" "dist/release-notes/v1.4.md" "dist/MoreCreate-v1.4.mcaddon" "d85090e25734fc602037fc9f2a8f6bcae041ec17" "--latest=false"
publish "v1.5" "More Create v1.5 - the cogwheel slot, properly" "dist/release-notes/v1.5.md" "dist/MoreCreate-v1.5.mcaddon" "75d81e386019ed9afe680026694d97e5ee66176f" "--latest=false"
publish "v1.6" "More Create v1.6 - the Recipe Browser, and the chain drive properly" "dist/release-notes/v1.6.md" "dist/MoreCreate-v1.6.mcaddon" "e689fd68d870ff38c6c4c744812f39bde9519254" "--latest=false"
publish "v1.7" "More Create v1.7 - the pause menu, and the chain drive from Create's own models" "dist/release-notes/v1.7.md" "dist/MoreCreate-v1.7.mcaddon" "claude/more-create-bedrock-mod-ccmzb3" "--latest"

echo "done - https://github.com/$REPO/releases"
